---
title: "PeacoQC"
author: "Maxim Lippeveld"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PeacoQC)
library(flowCore)
```

## QC

```{r}

base_path <- "D:/Experiment_data/weizmann/EhV/201"
channels <- c("IntensityMCTMRlogicle", "IntensityMCCy5logicle", "IntensityMCDAPIlogicle")

timepoints <- c("T0", "T2", "T3", "T4", "T5", "T6", "T7")
replicates <- c("R1", "R2", "R3")

grid <- expand.grid(timepoints, replicates)
for (i in 1:nrow(grid)) {
  fileName <- file.path(base_path, grid[i, 1], grid[i, 2], paste("fluor_", grid[i,1], "_", grid[i, 2], ".fcs", sep=""))
  ff <- flowCore::read.FCS(fileName, truncate_max_range = FALSE)

  peacoqc_res <- PeacoQC(
    ff=ff, 
    channels=channels, 
    determine_good_cells="all", 
    save_fcs=TRUE, 
    plot=TRUE,
    output_directory = "infected"
  )
}

PeacoQCHeatmap(report_location="infected/PeacoQC_results/PeacoQC_report.txt")

```
```{r}

base_path <- "D:/Experiment_data/weizmann/EhV/control"
channels <- c("IntensityMCTMRlogicle", "IntensityMCCy5logicle", "IntensityMCDAPIlogicle")

timepoints <- c("T0", "T4", "T5", "T6", "T7")
replicates <- c("R2", "R3")

grid <- expand.grid(timepoints, replicates)
for (i in 1:nrow(grid)) {
  fileName <- file.path(base_path, grid[i, 1], grid[i, 2], paste("fluor_", grid[i,1], "_", grid[i, 2], ".fcs", sep=""))
  ff <- flowCore::read.FCS(fileName, truncate_max_range = FALSE)

  peacoqc_res <- PeacoQC(
    ff=ff, 
    channels=channels, 
    determine_good_cells="all", 
    save_fcs=TRUE, 
    plot=TRUE,
    output_dir="controls"
  )
}

PeacoQCHeatmap(report_location="controls/PeacoQC_results/PeacoQC_report.txt")

```
