# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ehv/',
                'doc_host': 'https://mlippeve.github.io',
                'git_url': 'https://github.com/mlippeve/ehv/tree/master/',
                'lib_path': 'ehv'},
  'syms': { 'ehv.core': {},
            'ehv.correlation': {},
            'ehv.feature_comparison': {},
            'ehv.fluorescence_intensity': {},
            'ehv.gmm_clustering': {},
            'ehv.load': {},
            'ehv.masking': {},
            'ehv.mrna_content_regression': {},
            'ehv.normalization': {},
            'ehv.preprocessing_pipeline': {},
            'ehv.viral': {}}}