# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_scip_segmentation": "00_threshold_masking.ipynb"}

modules = ["masking.py"]

doc_url = "https://mlippeve.github.io/ehv/"

git_url = "https://github.com/mlippeve/ehv/tree/master/"

def custom_doc_links(name): return None
