# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_logicle_xform": "1e_viral_infection_progression.ipynb",
         "logicle_transform": "1e_viral_infection_progression.ipynb",
         "compare_features": "ehv_feature_comparison.ipynb",
         "load_config": "00_core.ipynb",
         "load_from_sqlite_db": "00_core.ipynb",
         "add_gating_table": "00_core.ipynb",
         "add_gate": "00_core.ipynb",
         "do_umap": "00_core.ipynb",
         "SelectFromCollection": "00_core.ipynb",
         "plot_gate": "00_core.ipynb",
         "plot_gate_zarr": "00_core.ipynb",
         "plot_gate_czi": "00_core.ipynb",
         "plot_scip_segmentation": "00_threshold_masking.ipynb",
         "load_raw_ideas_tree": "1a_load.ipynb",
         "check_should_load": "1a_load.ipynb",
         "load_raw_ideas_fcs": "1a_load.ipynb",
         "load_raw_ideas_dir": "1a_load.ipynb",
         "load_raw_ideas_dir_dask": "1a_load.ipynb",
         "clean_column_names": "1a_load.ipynb",
         "remove_unwanted_features": "1a_load.ipynb",
         "tag_columns": "1a_load.ipynb",
         "add_merged_col": "1a_load.ipynb",
         "func": "ehv_GMM_clustering_all_COI.ipynb",
         "n_components_search": "ehv_GMM_clustering_all_COI.ipynb",
         "define_dummy": "ehv_optimal_mrna_content_regression.ipynb",
         "define_mlp": "ehv_optimal_mrna_content_regression.ipynb",
         "define_xgb": "ehv_optimal_mrna_content_regression.ipynb",
         "define_sgd": "ehv_optimal_mrna_content_regression.ipynb",
         "definition_dict": "ehv_optimal_mrna_content_regression.ipynb",
         "objective": "ehv_optimal_mrna_content_regression.ipynb",
         "run_optimization": "ehv_optimal_mrna_content_regression.ipynb",
         "nested_cross_validation_with_hyperparam_optimization": "ehv_optimal_mrna_content_regression.ipynb",
         "nested_cross_validation_with_hyperparam_optimization_command": "ehv_optimal_mrna_content_regression.ipynb",
         "Correlation": "2c_selected_features_correlation_analysis.ipynb",
         "GroupedTransformer": "3c_preprocessing_pipeline_low.ipynb",
         "ColumnTransformer": "3c_preprocessing_pipeline_low.ipynb",
         "PandasVarianceThreshold": "3c_preprocessing_pipeline_low.ipynb",
         "make_pipeline_1": "3c_preprocessing_pipeline_ctrl.ipynb"}

modules = ["viral.py",
           "feature_comparison.py",
           "core.py",
           "masking.py",
           "load.py",
           "gmm_clustering.py",
           "mrna_content_regression.py",
           "fluorescence_intensity.py",
           "correlation.py",
           "preprocessing_pipeline.py"]

doc_url = "https://mlippeve.github.io/ehv/"

git_url = "https://github.com/mlippeve/ehv/tree/master/"

def custom_doc_links(name): return None
