# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_config": "00_core.ipynb",
         "load_from_sqlite_db": "00_core.ipynb",
         "add_gating_table": "00_core.ipynb",
         "add_gate": "00_core.ipynb",
         "do_umap": "00_core.ipynb",
         "load_raw_ideas_tree": "1a_load.ipynb",
         "check_should_load": "1a_load.ipynb",
         "load_raw_ideas_fcs": "1a_load.ipynb",
         "load_raw_ideas_dir": "1a_load.ipynb",
         "load_raw_ideas_dir_dask": "1a_load.ipynb",
         "remove_unwanted_features": "1a_load.ipynb",
         "tag_columns": "1a_load.ipynb",
         "add_merged_col": "1a_load.ipynb",
         "clean_column_names": "1a_load.ipynb",
         "apply_logicle": "2b_fluorescence_intensity_preprocessing.ipynb",
         "get_correlated_features": "2c_selected_features_correlation_analysis.ipynb",
         "knn_umap_plot": "3b_umap_reduction_of_all_COI.ipynb",
         "define_dummy": "4c_optimal_mrna_content_regression.ipynb",
         "define_mlp": "4c_optimal_mrna_content_regression.ipynb",
         "define_xgb": "4c_optimal_mrna_content_regression.ipynb",
         "define_sgd": "4c_optimal_mrna_content_regression.ipynb",
         "definition_dict": "4c_optimal_mrna_content_regression.ipynb",
         "objective": "4c_optimal_mrna_content_regression.ipynb",
         "run_optimization": "4c_optimal_mrna_content_regression.ipynb",
         "nested_cross_validation_with_hyperparam_optimization": "4c_optimal_mrna_content_regression.ipynb",
         "nested_cross_validation_with_hyperparam_optimization_command": "4c_optimal_mrna_content_regression.ipynb"}

modules = ["core.py",
           "load.py",
           "fluorescence_intensity.py",
           "correlation.py",
           "umap_all.py",
           "mrna_content_regression.py"]

doc_url = "https://mlippeve.github.io/ehv/"

git_url = "https://github.com/mlippeve/ehv/tree/master/"

def custom_doc_links(name): return None
