# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/1b_export.ipynb (unless otherwise specified).

__all__ = ['to_fcs']

# Cell
# export

import pandas
import os
import numpy
import seaborn
import logging
import matplotlib.pyplot as plt
from importlib import reload

# Cell

import fcswrite
from sklearn.preprocessing import OrdinalEncoder

# Cell

def to_fcs(df, filename, encode=["timepoint", "replicate", "label"]):
    df = df.copy()

    enc = OrdinalEncoder()
    df.loc[:, encode] = enc.fit_transform(df[encode])

    meta = {}
    for col, cats in zip(encode, enc.categories_):
        meta[col] = ",".join(cats.tolist())

    fcswrite.write_fcs(filename=filename, chn_names=df.columns.values, data=df, text_kw_pr=meta)