# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/3b_umap_reduction_of_all_COI.ipynb (unless otherwise specified).

__all__ = []

# Cell
# export

import pandas
import os
import numpy
import seaborn
import logging
import matplotlib.pyplot as plt
from matplotlib import cm
from importlib import reload
from ehv import core
from joblib import load, dump
from pathlib import Path
import uuid
import re

from ehv import load as e_load, core

plt.rcParams['figure.facecolor'] = 'white'

numpy.random.seed(42)

# Cell
import umap
from ehv import core, load as e_load, correlation
from matplotlib import cm
import matplotlib
import statsmodels.api as sm
from sklearn.neighbors import kneighbors_graph
import scipy.spatial.distance
import scipy.sparse
from sklearn.preprocessing import scale, robust_scale, minmax_scale
from sklearn.feature_selection import VarianceThreshold